import { Brawl } from '../interfaces/brawl.interface';

export const brawlers: Brawl[] = [
	{
		Name: 'Shelly',
		Rarity: 'Starting',
		Role: 'Damage Dealer',
		MoveSpeed: 770,
		Health: 7400,
		AttackRange: 7,
		AttackDamage: 600,
		SuperDamage: 5760,
		ReloadTime: 1.5,
		ProjectileSpeed: 3100,
		Image: 'shelly.png'
	},
	{
		Name: 'Colt',
		Rarity: 'Rare',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 8,
		AttackDamage: 480,
		SuperDamage: 1920,
		ReloadTime: 1.6,
		ProjectileSpeed: 3800,
		Image: 'colt.png'
	},
	{
		Name: 'Bull',
		Rarity: 'Rare',
		Role: 'Tank',
		MoveSpeed: 770,
		Health: 10000,
		AttackRange: 5,
		AttackDamage: 400,
		SuperDamage: 800,
		ReloadTime: 1.6,
		ProjectileSpeed: 2800,
		Image: 'bull.png'
	},
	{
		Name: 'Brock',
		Rarity: 'Rare',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 5200,
		AttackRange: 10,
		AttackDamage: 1100,
		SuperDamage: 520,
		ReloadTime: 2.1,
		ProjectileSpeed: 2870,
		Image: 'brock.png'
	},
	{
		Name: 'Rico',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'rico.png'
	},
	{
		Name: 'Spike',
		Rarity: 'Legendary',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 4000,
		AttackRange: 7.67,
		AttackDamage: 560,
		SuperDamage: 800,
		ReloadTime: 2.0,
		ProjectileSpeed: 3000,
		Image: 'spike.png'
	},
	{
		Name: 'Barley',
		Rarity: 'Rare',
		Role: 'Artillery',
		MoveSpeed: 720,
		Health: 5200,
		AttackRange: 7.5,
		AttackDamage: 760,
		SuperDamage: 800,
		ReloadTime: 2.1,
		ProjectileSpeed: 1050,
		Image: 'barley.png'
	},
	{
		Name: 'Jessie',
		Rarity: 'Super Rare',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 9,
		AttackDamage: 860,
		SuperDamage: 0,
		ReloadTime: 1.8,
		ProjectileSpeed: 3380,
		Image: 'jessie.png'
	},
	{
		Name: 'Nita',
		Rarity: 'Rare',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 8000,
		AttackRange: 6,
		AttackDamage: 1920,
		SuperDamage: 800,
		ReloadTime: 1.1,
		ProjectileSpeed: 3800,
		Image: 'nita.png'
	},
	{
		Name: 'Dynamike',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'dynamike.png'
	},
	{
		Name: 'El Primo',
		Rarity: 'Rare',
		Role: 'Tank',
		MoveSpeed: 770,
		Health: 10800,
		AttackRange: 3,
		AttackDamage: 1080,
		SuperDamage: 1200,
		ReloadTime: 0.8,
		ProjectileSpeed: 915,
		Image: 'elprimo.png'
	},
	{
		Name: 'Mortis',
		Rarity: 'Mythic',
		Role: 'Assassin',
		MoveSpeed: 820,
		Health: 6200,
		AttackRange: 2.67,
		AttackDamage: 1620,
		SuperDamage: 1260,
		ReloadTime: 2.4,
		ProjectileSpeed: 0,
		Image: 'mortis.png'
	},
	{
		Name: 'Crow',
		Rarity: 'Legendary',
		Role: 'Assassin',
		MoveSpeed: 820,
		Health: 4000,
		AttackRange: 8.33,
		AttackDamage: 520,
		SuperDamage: 1040,
		ReloadTime: 1.4,
		ProjectileSpeed: 3000,
		Image: 'crow.png'
	},
	{
		Name: 'Poco',
		Rarity: 'Rare',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 7200,
		AttackRange: 7.67,
		AttackDamage: 800,
		SuperDamage: 0,
		ReloadTime: 1.6,
		ProjectileSpeed: 2400,
		Image: 'poco.png'
	},
	{
		Name: 'Bo',
		Rarity: 'Epic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 7000,
		AttackRange: 8.33,
		AttackDamage: 780,
		SuperDamage: 1560,
		ReloadTime: 1.7,
		ProjectileSpeed: 1739,
		Image: 'bo.png'
	},
	{
		Name: 'Piper',
		Rarity: 'Epic',
		Role: 'Sniper',
		MoveSpeed: 720,
		Health: 4000,
		AttackRange: 10,
		AttackDamage: 1520,
		SuperDamage: 1200,
		ReloadTime: 2.0,
		ProjectileSpeed: 4000,
		Image: 'piper.png'
	},
	{
		Name: 'Pam',
		Rarity: 'Epic',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 8800,
		AttackRange: 8.33,
		AttackDamage: 260,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 3800,
		Image: 'pam.png'
	},
	{
		Name: 'Tara',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'tara.png'
	},
	{
		Name: 'Darryl',
		Rarity: 'Super Rare',
		Role: 'Tank',
		MoveSpeed: 770,
		Health: 8000,
		AttackRange: 7,
		AttackDamage: 440,
		SuperDamage: 800,
		ReloadTime: 1.6,
		ProjectileSpeed: 3800,
		Image: 'darryl.png'
	},
	{
		Name: 'Penny',
		Rarity: 'Super Rare',
		Role: 'Artillery',
		MoveSpeed: 720,
		Health: 6800,
		AttackRange: 8.67,
		AttackDamage: 1240,
		SuperDamage: 1680,
		ReloadTime: 2.0,
		ProjectileSpeed: 1520,
		Image: 'penny.png'
	},
	{
		Name: 'Frank',
		Rarity: 'Epic',
		Role: 'Tank',
		MoveSpeed: 720,
		Health: 10800,
		AttackRange: 6.67,
		AttackDamage: 1680,
		SuperDamage: 1680,
		ReloadTime: 0.8,
		ProjectileSpeed: 650,
		Image: 'frank.png'
	},
	{
		Name: 'Gene',
		Rarity: 'Mythic',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 6400,
		AttackRange: 5.67,
		AttackDamage: 960,
		SuperDamage: 300,
		ReloadTime: 2.0,
		ProjectileSpeed: 1800,
		Image: 'gene.png'
	},
	{
		Name: 'Tick',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'tick.png'
	},
	{
		Name: 'Leon',
		Rarity: 'Legendary',
		Role: 'Assassin',
		MoveSpeed: 820,
		Health: 4800,
		AttackRange: 6.67,
		AttackDamage: 660,
		SuperDamage: 0,
		ReloadTime: 1.9,
		ProjectileSpeed: 3200,
		Image: 'leon.png'
	},
	{
		Name: 'Rosa',
		Rarity: 'Rare',
		Role: 'Tank',
		MoveSpeed: 770,
		Health: 9000,
		AttackRange: 3.33,
		AttackDamage: 660,
		SuperDamage: 0,
		ReloadTime: 0.8,
		ProjectileSpeed: 1700,
		Image: 'rosa.png'
	},
	{
		Name: 'Carl',
		Rarity: 'Super Rare',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 7200,
		AttackRange: 8,
		AttackDamage: 660,
		SuperDamage: 1200,
		ReloadTime: 0.0,
		ProjectileSpeed: 3600,
		Image: 'carl.png'
	},
	{
		Name: 'Bibi',
		Rarity: 'Epic',
		Role: 'Tank',
		MoveSpeed: 820,
		Health: 8000,
		AttackRange: 3.67,
		AttackDamage: 1820,
		SuperDamage: 0,
		ReloadTime: 1.2,
		ProjectileSpeed: 0,
		Image: 'bibi.png'
	},
	{
		Name: '8-Bit',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: '8-bit.png'
	},
	{
		Name: 'Sandy',
		Rarity: 'Legendary',
		Role: 'Controller',
		MoveSpeed: 770,
		Health: 6000,
		AttackRange: 6.33,
		AttackDamage: 1260,
		SuperDamage: 120,
		ReloadTime: 1.8,
		ProjectileSpeed: 3500,
		Image: 'sandy.png'
	},
	{
		Name: 'Bea',
		Rarity: 'Epic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 3600,
		AttackRange: 10,
		AttackDamage: 1120,
		SuperDamage: 100,
		ReloadTime: 1.3,
		ProjectileSpeed: 3810,
		Image: 'bea.png'
	},
	{
		Name: 'Emz',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'emz.png'
	},
	{
		Name: 'Mr. P',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'mr._p.png'
	},
	{
		Name: 'Max',
		Rarity: 'Mythic',
		Role: 'Support',
		MoveSpeed: 820,
		Health: 6400,
		AttackRange: 8.33,
		AttackDamage: 320,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 2880,
		Image: 'max.png'
	},
	{
		Name: 'Jacky',
		Rarity: 'Super Rare',
		Role: 'Tank',
		MoveSpeed: 770,
		Health: 8800,
		AttackRange: 3.33,
		AttackDamage: 1520,
		SuperDamage: 1840,
		ReloadTime: 1.8,
		ProjectileSpeed: 0,
		Image: 'jacky.png'
	},
	{
		Name: 'Gale',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'gale.png'
	},
	{
		Name: 'Nani',
		Rarity: 'Epic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 8.67,
		AttackDamage: 1820,
		SuperDamage: 3080,
		ReloadTime: 1.5,
		ProjectileSpeed: 3000,
		Image: 'nani.png'
	},
	{
		Name: 'Sprout',
		Rarity: 'Mythic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 5200,
		AttackRange: 7.67,
		AttackDamage: 980,
		SuperDamage: 0,
		ReloadTime: 1.7,
		ProjectileSpeed: 1520,
		Image: 'sprout.png'
	},
	{
		Name: 'Surge',
		Rarity: 'Chromatic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6400,
		AttackRange: 6.5,
		AttackDamage: 900,
		SuperDamage: 0,
		ReloadTime: 1.7,
		ProjectileSpeed: 4000,
		Image: 'surge.png'
	},
	{
		Name: 'Colette',
		Rarity: 'Chromatic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6200,
		AttackRange: 8.5,
		AttackDamage: 920,
		SuperDamage: 0,
		ReloadTime: 1.5,
		ProjectileSpeed: 3800,
		Image: 'colette.png'
	},
	{
		Name: 'Amber',
		Rarity: 'Legendary',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 8,
		AttackDamage: 2000,
		SuperDamage: 1200,
		ReloadTime: 1.7,
		ProjectileSpeed: 4000,
		Image: 'amber.png'
	},
	{
		Name: 'Lou',
		Rarity: 'Chromatic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 7000,
		AttackRange: 7.67,
		AttackDamage: 560,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 1520,
		Image: 'lou.png'
	},
	{
		Name: 'Byron',
		Rarity: 'Mythic',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 4800,
		AttackRange: 8.33,
		AttackDamage: 980,
		SuperDamage: 0,
		ReloadTime: 1.5,
		ProjectileSpeed: 2400,
		Image: 'byron.png'
	},
	{
		Name: 'Edgar',
		Rarity: 'Epic',
		Role: 'Assassin',
		MoveSpeed: 820,
		Health: 6000,
		AttackRange: 2,
		AttackDamage: 1500,
		SuperDamage: 1000,
		ReloadTime: 0.7,
		ProjectileSpeed: 1500,
		Image: 'edgar.png'
	},
	{
		Name: 'Ruffs',
		Rarity: 'Mythic',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 6400,
		AttackRange: 8.33,
		AttackDamage: 560,
		SuperDamage: 1000,
		ReloadTime: 1.5,
		ProjectileSpeed: 3500,
		Image: 'ruffs.png'
	},
	{
		Name: 'Stu',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'stu.png'
	},
	{
		Name: 'Belle',
		Rarity: 'Chromatic',
		Role: 'Sharpshooter',
		MoveSpeed: 720,
		Health: 4800,
		AttackRange: 10,
		AttackDamage: 1540,
		SuperDamage: 500,
		ReloadTime: 1.5,
		ProjectileSpeed: 4000,
		Image: 'belle.png'
	},
	{
		Name: 'Squeak',
		Rarity: 'Mythic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 7000,
		AttackRange: 7.67,
		AttackDamage: 1540,
		SuperDamage: 1540,
		ReloadTime: 1.7,
		ProjectileSpeed: 1000,
		Image: 'squeak.png'
	},
	{
		Name: 'Grom',
		Rarity: 'Epic',
		Role: 'Artillery',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 7.67,
		AttackDamage: 1740,
		SuperDamage: 2000,
		ReloadTime: 2.1,
		ProjectileSpeed: 1100,
		Image: 'grom.png'
	},
	{
		Name: 'Buzz',
		Rarity: 'Chromatic',
		Role: 'Assassin',
		MoveSpeed: 770,
		Health: 9200,
		AttackRange: 2.5,
		AttackDamage: 1120,
		SuperDamage: 0,
		ReloadTime: 1.2,
		ProjectileSpeed: 0,
		Image: 'buzz.png'
	},
	{
		Name: 'Griff',
		Rarity: 'Epic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 7600,
		AttackRange: 8.33,
		AttackDamage: 2600,
		SuperDamage: 3640,
		ReloadTime: 1.7,
		ProjectileSpeed: 3700,
		Image: 'griff.png'
	},
	{
		Name: 'Ash',
		Rarity: 'Chromatic',
		Role: 'Tank',
		MoveSpeed: 770,
		Health: 10400,
		AttackRange: 4.33,
		AttackDamage: 1160,
		SuperDamage: 180,
		ReloadTime: 2.1,
		ProjectileSpeed: 1800,
		Image: 'ash.png'
	},
	{
		Name: 'Meg',
		Rarity: 'Legendary',
		Role: 'Tank',
		MoveSpeed: 720,
		Health: 3300,
		AttackRange: 6.67,
		AttackDamage: 360,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 4800,
		Image: 'meg.png'
	},
	{
		Name: 'Lola',
		Rarity: 'Chromatic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6700,
		AttackRange: 8.33,
		AttackDamage: 390,
		SuperDamage: 0,
		ReloadTime: 1.5,
		ProjectileSpeed: 3800,
		Image: 'lola.png'
	},
	{
		Name: 'Fang',
		Rarity: 'Chromatic',
		Role: 'Assassin',
		MoveSpeed: 820,
		Health: 7500,
		AttackRange: 2,
		AttackDamage: 1650,
		SuperDamage: 1200,
		ReloadTime: 1.0,
		ProjectileSpeed: 4350,
		Image: 'fang.png'
	},
	{
		Name: 'Eve',
		Rarity: 'Chromatic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 5600,
		AttackRange: 7.33,
		AttackDamage: 1480,
		SuperDamage: 1480,
		ReloadTime: 1.5,
		ProjectileSpeed: 3200,
		Image: 'eve.png'
	},
	{
		Name: 'Janet',
		Rarity: 'Chromatic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 8,
		AttackDamage: 1320,
		SuperDamage: 1000,
		ReloadTime: 1.5,
		ProjectileSpeed: 1000,
		Image: 'janet.png'
	},
	{
		Name: 'Bonnie',
		Rarity: 'Chromatic',
		Role: 'Artillery',
		MoveSpeed: 770,
		Health: 7400,
		AttackRange: 9,
		AttackDamage: 1350,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 3200,
		Image: 'bonnie.png'
	},
	{
		Name: 'Otis',
		Rarity: 'Chromatic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 6800,
		AttackRange: 7.33,
		AttackDamage: 1180,
		SuperDamage: 100,
		ReloadTime: 1.6,
		ProjectileSpeed: 1520,
		Image: 'otis.png'
	},
	{
		Name: 'Sam',
		Rarity: 'Chromatic',
		Role: 'Tank',
		MoveSpeed: 770,
		Health: 9000,
		AttackRange: 5.33,
		AttackDamage: 1140,
		SuperDamage: 2800,
		ReloadTime: 0.9,
		ProjectileSpeed: 1520,
		Image: 'sam.png'
	},
	{
		Name: 'Gus',
		Rarity: 'Super Rare',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 5800,
		AttackRange: 9,
		AttackDamage: 1140,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 3000,
		Image: 'gus.png'
	},
	{
		Name: 'Buster',
		Rarity: 'Chromatic',
		Role: 'Tank',
		MoveSpeed: 720,
		Health: 8000,
		AttackRange: 5.33,
		AttackDamage: 1340,
		SuperDamage: 200,
		ReloadTime: 1.6,
		ProjectileSpeed: 4000,
		Image: 'buster.png'
	},
	{
		Name: 'Chester',
		Rarity: 'Legendary',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6400,
		AttackRange: 7,
		AttackDamage: 800,
		SuperDamage: 0,
		ReloadTime: 1.8,
		ProjectileSpeed: 3200,
		Image: 'chester.png'
	},
	{
		Name: 'Gray',
		Rarity: 'Mythic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 6400,
		AttackRange: 7.33,
		AttackDamage: 1280,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 3000,
		Image: 'gray.png'
	},
	{
		Name: 'Mandy',
		Rarity: 'Chromatic',
		Role: 'Artillery',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 10.67,
		AttackDamage: 1480,
		SuperDamage: 1000,
		ReloadTime: 1.5,
		ProjectileSpeed: 4800,
		Image: 'mandy.png'
	},
	{
		Name: 'R-T',
		Rarity: 'Chromatic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 7200,
		AttackRange: 7.33,
		AttackDamage: 1200,
		SuperDamage: 1400,
		ReloadTime: 1.9,
		ProjectileSpeed: 1520,
		Image: 'rt.png'
	},
	{
		Name: 'Willow',
		Rarity: 'Mythic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 4800,
		AttackRange: 6.67,
		AttackDamage: 1240,
		SuperDamage: 0,
		ReloadTime: 1.5,
		ProjectileSpeed: 1520,
		Image: 'willow.png'
	},
	{
		Name: 'Maisie',
		Rarity: 'Chromatic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 6600,
		AttackRange: 6.67,
		AttackDamage: 1520,
		SuperDamage: 1280,
		ReloadTime: 1.6,
		ProjectileSpeed: 4000,
		Image: 'maisie.png'
	},
	{
		Name: 'Hank',
		Rarity: 'Epic',
		Role: 'Tank',
		MoveSpeed: 720,
		Health: 9400,
		AttackRange: 6.67,
		AttackDamage: 3080,
		SuperDamage: 2000,
		ReloadTime: 1.6,
		ProjectileSpeed: 1520,
		Image: 'hank.png'
	},
	{
		Name: 'Cordelius',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'cordelius.png'
	},
	{
		Name: 'Doug',
		Rarity: 'Rare',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 7200,
		AttackRange: 5,
		AttackDamage: 1400,
		SuperDamage: 0,
		ReloadTime: 1.3,
		ProjectileSpeed: 1520,
		Image: 'doug.png'
	},
	{
		Name: 'Pearl',
		Rarity: 'Chromatic',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 7800,
		AttackRange: 6.33,
		AttackDamage: 660,
		SuperDamage: 1320,
		ReloadTime: 2.1,
		ProjectileSpeed: 1520,
		Image: 'pearl.png'
	},
	{
		Name: 'Chuck',
		Rarity: 'Mythic',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 8000,
		AttackRange: 7.33,
		AttackDamage: 1240,
		SuperDamage: 1480,
		ReloadTime: 1.8,
		ProjectileSpeed: 3700,
		Image: 'chuck.png'
	},
	{
		Name: 'Charlie',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'charlie.png'
	},
	{
		Name: 'Mico',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'mico.png'
	},
	{
		Name: 'Kit',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'kit.png'
	},
	{
		Name: 'Larry & Lawrie',
		Rarity: 'Epic',
		Role: 'Artillery',
		MoveSpeed: 720,
		Health: 7000,
		AttackRange: 4.33,
		AttackDamage: 1400,
		SuperDamage: 0,
		ReloadTime: 1.4,
		ProjectileSpeed: 1520,
		Image: 'larry_lawrie.png'
	},
	{
		Name: 'Melodie',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'melodie.png'
	},
	{
		Name: 'Angelo',
		Rarity: 'Legendary',
		Role: 'Artillery',
		MoveSpeed: 720,
		Health: 5400,
		AttackRange: 7.33,
		AttackDamage: 1200,
		SuperDamage: 0,
		ReloadTime: 2.0,
		ProjectileSpeed: 3200,
		Image: 'angelo.png'
	},
	{
		Name: 'Draco',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'draco.png'
	},
	{
		Name: 'Lily',
		Rarity: 'Epic',
		Role: 'Support',
		MoveSpeed: 720,
		Health: 6000,
		AttackRange: 6,
		AttackDamage: 920,
		SuperDamage: 0,
		ReloadTime: 0,
		ProjectileSpeed: 0,
		Image: 'lily.png'
	},
	{
		Name: 'Berry',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'berry.png'
	},
	{
		Name: 'Clancy',
		Rarity: 'Legendary',
		Role: 'Controller',
		MoveSpeed: 720,
		Health: 7000,
		AttackRange: 8,
		AttackDamage: 940,
		SuperDamage: 0,
		ReloadTime: 0,
		ProjectileSpeed: 0,
		Image: 'clancy.png'
	},
	{
		Name: 'Moe',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'moe.png'
	},
	{
		Name: 'Kenji',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'kenji.png'
	},
	{
		Name: 'Shade',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'shade.png'
	},
	{
		Name: 'Juju',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'juju.png'
	},
	{
		Name: 'Meeple',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'meeple.png'
	},
	{
		Name: 'Ollie',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'ollie.png'
	},
	{
		Name: 'Lumi',
		Rarity: 'Legendary',
		Role: 'Damage Dealer',
		MoveSpeed: 720,
		Health: 4400,
		AttackRange: 7.67,
		AttackDamage: 1400,
		SuperDamage: 0,
		ReloadTime: 0,
		ProjectileSpeed: 0,
		Image: 'lumi.png'
	},
	{
		Name: 'Finx',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'finx.png'
	},
	{
		Name: 'Jae-Yong',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'jae-yong.png'
	},
	{
		Name: 'Kaze',
		Rarity: 'Unknown',
		Role: 'Unknown',
		MoveSpeed: 0,
		Health: 0,
		AttackRange: 0,
		AttackDamage: 0,
		Image: 'kaze.png'
	}
];
